### ISSUE TITLE
not initializing with more than 5 stars when total stars equals 10

### ISSUE THREAD

**Issue by sandrumirceaioan** [riteshgandhi/ng-star-rating#12]

**Comment by riteshgandhi** [comment]
Hey, I just tried with below two ratings. worked for me. can you give me some example?

<star-rating value="0" 
    totalstars="10" 
    checkedcolor="yellow" 
    uncheckedcolor="black" 
    size="50" 
    readonly=false>
</star-rating>

<star-rating value="4" 
    totalstars="10" 
    checkedcolor="yellow" 
    uncheckedcolor="black" 
    size="50" 
    readonly=false>
</star-rating>

**Comment by sandrumirceaioan** [comment]
I tried this directive because it was pretty easy to use looking at specs, but then:

1. First issue:
`<star-rating value="7" totalstars="10" checkedcolor="yellow" uncheckedcolor="black" size="24" readonly=false></star-rating>` 
![7stars](https://user-images.githubusercontent.com/18594144/73612744-ee451e80-45f6-11ea-9b1e-31b669e8136d.png)
So it is set with value 7, but showing only 5 yellow stars.

2. Second issue:
I need to initialize like this:

in my component class add something like this
public rating: number = 7.5;

in html template use your directive like this
`<star-rating [value]="rating" totalstars="10" checkedcolor="yellow" uncheckedcolor="black" size="24" readonly=false></star-rating>`

But not working, it only shows maximum 5 start out of 10.

Angular version: 8.2

**Comment by riteshgandhi** [comment]
> I tried this directive because it was pretty easy to use looking at specs, but then:
> 
> 1. First issue:
>    `<star-rating value="7" totalstars="10" checkedcolor="yellow" uncheckedcolor="black" size="24" readonly=false></star-rating>`
>    ![7stars](https://user-images.githubusercontent.com/18594144/73612744-ee451e80-45f6-11ea-9b1e-31b669e8136d.png)
>    So it is set with value 7, but showing only 5 yellow stars.
> 2. Second issue:
>    I need to initialize like this:
> 
> in my component class add something like this
> public rating: number = 7.5;
> 
> in html template use your directive like this
> `<star-rating [value]="rating" totalstars="10" checkedcolor="yellow" uncheckedcolor="black" size="24" readonly=false></star-rating>`
> 
> But not working, it only shows maximum 5 start out of 10.
> 
> Angular version: 8.2

thanks for choosing ng-starrating. I'll test and fix this issue asap

**Comment by riteshgandhi** [comment]
> I tried this directive because it was pretty easy to use looking at specs, but then:
> 
> 1. First issue:
>    `<star-rating value="7" totalstars="10" checkedcolor="yellow" uncheckedcolor="black" size="24" readonly=false></star-rating>`
>    ![7stars](https://user-images.githubusercontent.com/18594144/73612744-ee451e80-45f6-11ea-9b1e-31b669e8136d.png)
>    So it is set with value 7, but showing only 5 yellow stars.
> 2. Second issue:
>    I need to initialize like this:
> 
> in my component class add something like this
> public rating: number = 7.5;
> 
> in html template use your directive like this
> `<star-rating [value]="rating" totalstars="10" checkedcolor="yellow" uncheckedcolor="black" size="24" readonly=false></star-rating>`
> 
> But not working, it only shows maximum 5 start out of 10.
> 
> Angular version: 8.2

hello, this issue is fixed with new version 1.0.12. Can you give it a try?

**Comment by riteshgandhi** [comment]
@sandrumirceaioan 

Hello, if you are not using any other rating component then try the latest version (https://www.npmjs.com/package/ng-starrating). Issue you reported is fixed and it is also upgraded to latest angular version.
