### ISSUE TITLE
Is it possible to hide the star rate value tool tip ??

### ISSUE THREAD

**Issue by srivigneshwara** [riteshgandhi/ng-star-rating#16]
Hi @riteshgandhi ,

I have a requirement where i need to hide the tool tip of the star value .
please find the image which need to be hidden .
![issue](https://user-images.githubusercontent.com/46557250/74833097-d4b60d80-533e-11ea-8ffd-19a50924bd31.png)

**Comment by riteshgandhi** [comment]
> Hi @riteshgandhi ,
> 
> I have a requirement where i need to hide the tool tip of the star value .
> please find the image which need to be hidden .
> ![issue](https://user-images.githubusercontent.com/46557250/74833097-d4b60d80-533e-11ea-8ffd-19a50924bd31.png)

this can be done. I'll add new property to hide tooltip.

**Comment by srivigneshwara** [comment]
Hi @riteshgandhi 
let me know once the property is added
Thanks,

**Comment by riteshgandhi** [comment]
Moved to feature request. It'll be implemented soon

https://github.com/riteshgandhi/ng-star-rating/issues/19
