### ISSUE TITLE
Error "An accessor cannot be declared in an ambient context"

### ISSUE THREAD

**Issue by MaryCooperGD** [riteshgandhi/ng-star-rating#17]
I've added the component and started the app with `ng serve` but it's giving these errors:

![image](https://user-images.githubusercontent.com/12009396/75138883-94161580-56eb-11ea-9e2d-ee540642388c.png)

Versions:

```
Angular CLI: 8.3.23
Node: 12.14.1
OS: win32 x64
Angular: 8.2.14
```

**Comment by riteshgandhi** [comment]
> I've added the component and started the app with `ng serve` but it's giving these errors:
> 
> ![image](https://user-images.githubusercontent.com/12009396/75138883-94161580-56eb-11ea-9e2d-ee540642388c.png)
> 
> Versions:
> 
> ```
> Angular CLI: 8.3.23
> Node: 12.14.1
> OS: win32 x64
> Angular: 8.2.14
> ```

try upgrading typescript to latest version. Also check the demo project

**Comment by riteshgandhi** [comment]
@MaryCooperGD - let me know if you still have issues with ng-starrating component

**Comment by riteshgandhi** [comment]
closing this issue as did not get any response from @MaryCooperGD .
