### ISSUE TITLE
How to get 10 stars instead of 5 ?

### ISSUE THREAD

**Issue by jnjaga24** [riteshgandhi/ng-star-rating#6]
I need to implement 10 stars rating functionality. how can i achieve this with ng-star-rating package?

**Comment by riteshgandhi** [comment]
I'm planning to make that (number of Stars) parameterized. That should do it. However, It might take some time.

**Comment by tillkuhn** [comment]
I'd also appreciate if this could be parameterizable, in this case my requirements tell me to display only 3 stars instead 5 :-)

**Comment by riteshgandhi** [comment]
Thanks for using the component. I am currently working on this requirement. Will be publishing it soon.

![multi-star-rating](https://user-images.githubusercontent.com/8303810/69513503-f6595180-0f15-11ea-8324-08331574873f.JPG)

**Comment by riteshgandhi** [comment]
@jnjaga24, @tillkuhn 

This feature is now available. Kindly download version [1.0.9](https://www.npmjs.com/package/ng-starrating/v/1.0.9)

You can use new property "totalstars"

**Comment by tillkuhn** [comment]
Thanks @jnjaga24, works almost perfectly. The flaw: When `readonly` is `true`, nothing is rendered if `totalstars` is specified. If I set `readonly` to `false` it works, if I remove `totalstars` it also works (but with 5 stars of course). Affected version 1.0.9 just pulled from npm. Can you pls check again?

`<star-rating [value]="e.score" [totalstars]="totalstars"  checkedcolor="gold" uncheckedcolor="gray" readonly="true" ></star-rating>`

**Comment by riteshgandhi** [comment]
@tillkuhn 

Can you check now with [1.0.10](https://www.npmjs.com/package/ng-starrating/v/1.0.10)?

**Comment by tillkuhn** [comment]
@riteshgandhi works, thanks a lot! It's already deploying. And congratulations to your 10th Github star on this project - it even matches the subject of this issue :-)

**Comment by riteshgandhi** [comment]
yw, closing the issue
