### ISSUE TITLE
how to implement/manage  multiple star-rating in ngFor angular

### ISSUE THREAD

**Issue by AsimAziz** [riteshgandhi/ng-star-rating#9]
`<div *ngFor="let item of supplierName;">
                             <div class="row">
                             <div class="col-sm-">                                 
                                 <div class="row">                                 
                                     <div class="col-sm-7" style="margin-top: 15px">
                                        {{item.companyName}}                                     
                                            
                                        </div>
                                 </div>
                             </div>
                             <div class="col-sm-6">
                                <p style="margin-top: 8px">
                                    <star-rating id="id_{{item._id}}"  [value]="this.star" checkedcolor="green" uncheckedcolor="red" size="24px"   readonly="false" (rate)="onRate($event, item._id)"></star-rating>
                                </p>
                             </div>`

**Comment by riteshgandhi** [comment]
there's a demo app I created. Below is the url. Let me know if that's something you are looking for 

https://github.com/riteshgandhi/ng-star-rating/blob/master/src/app/app.component.html
